# Revision 239 Jagex interface component names used by bootstrap content.
[components]
"orbs:runbutton" = 10485788
"settings_side:runmode" = 7602206
"logout:logout" = 11927560
"stats:attack" = 20971521
"stats:strength" = 20971522
"stats:defence" = 20971523
"stats:ranged" = 20971524
"stats:prayer" = 20971525
"stats:magic" = 20971526
"stats:runecraft" = 20971527
"stats:construction" = 20971528
"stats:hitpoints" = 20971529
"stats:agility" = 20971530
"stats:herblore" = 20971531
"stats:thieving" = 20971532
"stats:crafting" = 20971533
"stats:fletching" = 20971534
"stats:slayer" = 20971535
"stats:hunter" = 20971536
"stats:mining" = 20971537
"stats:smithing" = 20971538
"stats:fishing" = 20971539
"stats:cooking" = 20971540
"stats:firemaking" = 20971541
"stats:woodcutting" = 20971542
"stats:farming" = 20971543
"toplevel_osrs_stretch:mainmodal" = 10551312
"toplevel_osrs_stretch:side2" = 10551374
"poh_options:title" = 24248320
"poh_options:viewer" = 24248321
"poh_options:on_text" = 24248322
"poh_options:off_text" = 24248323
"poh_options:building_mode" = 24248324
"poh_options:building_mode_on" = 24248325
"poh_options:building_mode_off" = 24248326
"poh_options:teleport_inside" = 24248327
"poh_options:teleport_inside_on" = 24248328
"poh_options:teleport_inside_off" = 24248329
"poh_options:default_building_mode" = 24248330
"poh_options:default_building_mode_on" = 24248331
"poh_options:default_building_mode_off" = 24248332
"poh_options:doors" = 24248333
"poh_options:doors_closed" = 24248334
"poh_options:icon_doors_closed" = 24248335
"poh_options:icon_doors_open" = 24248336
"poh_options:doors_open" = 24248337
"poh_options:icon_doors_none" = 24248338
"poh_options:doors_none" = 24248339
"poh_options:expel_guests" = 24248340
"poh_options:leave_house" = 24248341
"poh_options:call_servant" = 24248342
"poh_options:footer" = 24248343
"poh_options:close" = 24248344
"bookofscrolls:title" = 39124996
"bookofscrolls:teleportscroll_nardah" = 39124997
"bookofscrolls:text_nardah" = 39124999
"bookofscrolls:title_nardah" = 39125000
"bookofscrolls:teleportscroll_digsite" = 39125001
"bookofscrolls:text_digsite" = 39125003
"bookofscrolls:title_digsite" = 39125004
"bookofscrolls:teleportscroll_feldip" = 39125005
"bookofscrolls:text_feldip" = 39125007
"bookofscrolls:title_feldip" = 39125008
"bookofscrolls:teleportscroll_lunarisle" = 39125009
"bookofscrolls:text_lunarisle" = 39125011
"bookofscrolls:title_lunar" = 39125012
"bookofscrolls:teleportscroll_mortton" = 39125013
"bookofscrolls:text_mortton" = 39125015
"bookofscrolls:title_mortton" = 39125016
"bookofscrolls:teleportscroll_pestcontrol" = 39125017
"bookofscrolls:text_pestcontrol" = 39125019
"bookofscrolls:title_pestcontrol" = 39125020
"bookofscrolls:teleportscroll_piscatoris" = 39125021
"bookofscrolls:text_piscatoris" = 39125023
"bookofscrolls:title_piscatoris" = 39125024
"bookofscrolls:teleportscroll_taibwo" = 39125025
"bookofscrolls:text_taibwo" = 39125027
"bookofscrolls:title_taibwo" = 39125028
"bookofscrolls:teleportscroll_elf" = 39125029
"bookofscrolls:text_elf" = 39125031
"bookofscrolls:title_elf" = 39125032
"bookofscrolls:teleportscroll_mosles" = 39125033
"bookofscrolls:text_mosles" = 39125035
"bookofscrolls:title_mosles" = 39125036
"bookofscrolls:teleportscroll_lumberyard" = 39125037
"bookofscrolls:text_lumberyard" = 39125039
"bookofscrolls:title_lumberyard" = 39125040
"bookofscrolls:teleportscroll_zulandra" = 39125041
"bookofscrolls:text_zulandra" = 39125043
"bookofscrolls:title_zulandra" = 39125044
"bookofscrolls:text_cerberus" = 39125046
"bookofscrolls:title_cerberus" = 39125047
"bookofscrolls:teleportscroll_cerberus" = 39125048
"bookofscrolls:teleportscroll_revenants" = 39125049
"bookofscrolls:teleportscroll_watson" = 39125050
"bookofscrolls:text_revenants" = 39125052
"bookofscrolls:title_revenants" = 39125053
"bookofscrolls:teleportscroll_guthixian_temple" = 39125054
"bookofscrolls:teleportscroll_spidercave" = 39125055
"bookofscrolls:teleportscroll_colossal_wyrm" = 39125065
"bookofscrolls:teleportscroll_chasmoffire" = 39125066
"wornitems:equipment" = 25362433
"wornitems:pricechecker" = 25362435
"wornitems:deathkeep" = 25362437
"wornitems:call_follower" = 25362439
"tournament_supplies:universe" = 6553600
"tournament_supplies:switchlayer" = 6553602
"tournament_supplies:item_container" = 6553603
"tournament_supplies:list" = 6553604
"tournament_supplies:scrollbar" = 6553605
"tournament_supplies:search" = 6553606
"tournament_supplies:loadout_container" = 6553607
"tournament_supplies:inv" = 6553609
"tournament_supplies:catalogue_list" = 6553631
"tournament_supplies:loadout_apply" = 6553633

[client_scripts]
"meslayer:countdialog" = 108
"meslayer:objdialog" = 750
"meslayer:close" = 101
"tournament_supplies:populate_loadouts" = 2687
"tournament_supplies:switchlayer" = 2697
"toplevel:mainmodal_open" = 2524

[client_constants]
"meslayer_mode:countdialog" = 7
"meslayer_mode:objdialog" = 14

[gameframe]
top_level = 161

[[gameframe.sub_interfaces]]
destination = 10551392
interface = 162

[[gameframe.sub_interfaces]]
destination = 10551302
interface = 651

[[gameframe.sub_interfaces]]
destination = 10551301
interface = 708

[[gameframe.sub_interfaces]]
destination = 10551389
interface = 163

[[gameframe.sub_interfaces]]
destination = 10551298
interface = 303

[[gameframe.sub_interfaces]]
destination = 10551329
interface = 160

[[gameframe.sub_interfaces]]
destination = 10551305
interface = 122

[[gameframe.sub_interfaces]]
destination = 10551331
interface = 728

[[gameframe.sub_interfaces]]
destination = 10551332
interface = 896

[[gameframe.sub_interfaces]]
destination = 10551373
interface = 320

[[gameframe.sub_interfaces]]
destination = 10551374
interface = 629

[[gameframe.sub_interfaces]]
destination = 41222187
interface = 259

[[gameframe.sub_interfaces]]
destination = 10551375
interface = 149

[[gameframe.sub_interfaces]]
destination = 10551376
interface = 387

[[gameframe.sub_interfaces]]
destination = 10551377
interface = 541

[[gameframe.sub_interfaces]]
destination = 10551378
interface = 218

[[gameframe.sub_interfaces]]
destination = 10551381
interface = 429

[[gameframe.sub_interfaces]]
destination = 10551380
interface = 109

[[gameframe.sub_interfaces]]
destination = 10551382
interface = 182

[[gameframe.sub_interfaces]]
destination = 10551383
interface = 116

[[gameframe.sub_interfaces]]
destination = 10551384
interface = 216

[[gameframe.sub_interfaces]]
destination = 10551385
interface = 239

[[gameframe.sub_interfaces]]
destination = 10551379
interface = 707

[[gameframe.sub_interfaces]]
destination = 46333959
interface = 7

[[gameframe.sub_interfaces]]
destination = 10551372
interface = 593

[[gameframe.initial_inventories]]
component = 64209
inventory = 93
source = "inventory"

[[gameframe.initial_inventories]]
component = 64208
inventory = 94
source = "worn"
