ALTER TABLE players
    ADD COLUMN gender SMALLINT NOT NULL DEFAULT 0 CHECK (gender BETWEEN 0 AND 1),
    ADD COLUMN hair_kit INTEGER NOT NULL DEFAULT 0 CHECK (hair_kit BETWEEN 0 AND 1791),
    ADD COLUMN jaw_kit INTEGER NOT NULL DEFAULT 10 CHECK (jaw_kit BETWEEN 0 AND 1791),
    ADD COLUMN torso_kit INTEGER NOT NULL DEFAULT 18 CHECK (torso_kit BETWEEN 0 AND 1791),
    ADD COLUMN arms_kit INTEGER NOT NULL DEFAULT 26 CHECK (arms_kit BETWEEN 0 AND 1791),
    ADD COLUMN hands_kit INTEGER NOT NULL DEFAULT 33 CHECK (hands_kit BETWEEN 0 AND 1791),
    ADD COLUMN legs_kit INTEGER NOT NULL DEFAULT 36 CHECK (legs_kit BETWEEN 0 AND 1791),
    ADD COLUMN feet_kit INTEGER NOT NULL DEFAULT 42 CHECK (feet_kit BETWEEN 0 AND 1791),
    ADD COLUMN hair_color SMALLINT NOT NULL DEFAULT 0 CHECK (hair_color BETWEEN 0 AND 29),
    ADD COLUMN torso_color SMALLINT NOT NULL DEFAULT 0 CHECK (torso_color BETWEEN 0 AND 28),
    ADD COLUMN legs_color SMALLINT NOT NULL DEFAULT 0 CHECK (legs_color BETWEEN 0 AND 28),
    ADD COLUMN feet_color SMALLINT NOT NULL DEFAULT 0 CHECK (feet_color BETWEEN 0 AND 5),
    ADD COLUMN skin_color SMALLINT NOT NULL DEFAULT 0 CHECK (skin_color BETWEEN 0 AND 13);
